name: CI
on:
  push:
    branches:
      - staging
      - trying

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.8.0, 1.15.0, 1.20.0, 1.26.0, 1.31.0, stable, beta, nightly]
    steps:
      - name: Rust install
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: cargo build
      - name: Test
        run: ./ci/test_full.sh

  # try a target that doesn't have std at all
  no_std:
    name: No Std
    runs-on: ubuntu-latest
    steps:
      - name: Rust install
        uses: dtolnay/rust-toolchain@stable
        with:
          target: thumbv6m-none-eabi
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: cargo build --target thumbv6m-none-eabi --no-default-features --features i128

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Rust install
        uses: dtolnay/rust-toolchain@1.62.0
        with:
          components: rustfmt
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check formatting
        run: cargo fmt --all --check
