name: PR
on:
  pull_request:

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [1.8.0, stable]
    steps:
      - name: Rust install
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: Test
        run: ./ci/test_full.sh

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Rust install
        uses: dtolnay/rust-toolchain@1.62.0
        with:
          components: rustfmt
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check
